FROM cypress/browsers:node12.14.1-chrome85-ff81 AS builder

COPY package.json .
RUN npm i
COPY . .

FROM builder AS test
ARG CYPRESS_RECORD_KEY
ENV CYPRESS_RECORD_KEY=$CYPRESS_RECORD_KEY

ARG BASEURL
ENV BASEURL=$BASEURL

ARG APIURL
ENV APIURL=$APIURL

ARG CNAME
ENV CNAME=$CNAME

ARG PARALLEL
ENV PARALLEL=$PARALLEL

ARG CI_BUILD_ID
ENV CI_BUILD_ID=$CI_BUILD_ID
RUN echo $CI_BUILD_ID

RUN yarn cy:run:ci; exit 0